### ISSUE TITLE
win7 git-bash 初始化报错

### ISSUE THREAD

**Issue by mtmzorro** [lemonleon/jcube-cli#1]
```
$  jcube init react my-project
C:\Users\Administrator\AppData\Roaming\nvm\v4.4.7\node_modules\jcube-cli\lib\generate.js:10
var production = (/(\w+)_(\w+)_(\w+)\\$/gmi.exec(tmpPath))[2];
                                                          ^

TypeError: Cannot read property '2' of null
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\nvm\v4.4.7\node_modules\jcube-cli\lib\generate.js:10:59)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\nvm\v4.4.7\node_modules\jcube-cli\bin\jcube-init.js:10:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

```

win7 node:6.10.3 4.4.7 均报以上错误

**Comment by lemonleon** [comment]
已修复 :)
